kind: pipeline
type: docker
name: paulgg-enterprises

steps:
- name: build
  image: "node:alpine"
  commands:
  - yarn
  - yarn build

- name: copyfiles
  image: appleboy/drone-scp
  settings:
    host:
      from_secret: HOST
    port: 22
    key:
      from_secret: SSH_KEY
    source: dist
    target: ~/apps/paulgg-enterprises
    username:
      from_secret: USER
  when:
    branch: 
    - master
    event: 
    - push

- name: deploy
  image: appleboy/drone-ssh
  settings:
    host:
      from_secret: HOST
    port: 22
    key:
      from_secret: SSH_KEY
    username:
      from_secret: USER
    script: bash ~/apps/paulgg-enterprises/deploy.sh
  when:
    branch:
    - master
    event:
    - push